theme: minima

minima:
  skin: dark

# Site settings
title: Heric Libong's GitHub Page
email: hericlibong@gmail.com
description: >- 
  This is Heric Libong's personal website, built with GitHub Pages and the Minima theme.
baseurl: ""
url: "https://hericlibong.github.io"
social_media_links:
  - label: "GitHub"
    url: "https://github.com/hericlibong"

# Build settings
markdown: kramdown

# Navigation links
header_pages:
  - about.md
  - blog.md

# Include the posts in the home layout
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

# Enable future posts
future: true


# Forcing a rebuild
# This is a comment to force rebuild
